CREATE DATABASE ShopDB; 
USE ShopDB; 

CREATE TABLE Countries (
    ID INT,
    Name VARCHAR(50),
    PRIMARY KEY (ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS GeoIPCache (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    IPRange VARCHAR(50) NOT NULL,
    CountryID INT NOT NULL,
    INDEX (IPRange),
    INDEX (CountryID)
) ENGINE=MEMORY;

CREATE TABLE IF NOT EXISTS ProductDescription (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Description TEXT NOT NULL,
    ProductID INT NOT NULL,
    CountryID INT NOT NULL,
    INDEX (ProductID),
    INDEX (CountryID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Logs (
    ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `Timestamp` DATETIME DEFAULT CURRENT_TIMESTAMP,
    Message VARCHAR(1024)
) ENGINE=BLACKHOLE;
CREATE TABLE IF NOT EXISTS ProductReporting (
    `Date` DATE NOT NULL,
    ProductName VARCHAR(255) NOT NULL,
    Orders INT NOT NULL
) ENGINE=CSV;
